service: o-trade

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  region: eu-west-1
      
functions:
  home:
    handler: handler.home
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
